#!/usr/bin/env python3
"""Regenerate app/esi/scope_map.py from CCP's published ESI OpenAPI spec.

    python3 scripts/gen_esi_scope_map.py                    # fetch the live spec
    python3 scripts/gen_esi_scope_map.py path/to/openapi.json

The generated module is what ESIClient's scope guard consults before every
authenticated call: which ESI scope an operation needs, which in-game corp
roles it additionally requires, and which operations are public. It is built
from the spec rather than from a grep of this codebase so the table is complete
by construction — a new call site cannot slip past the guard because nobody
remembered to add its endpoint.

Run it when CCP adds an endpoint Vigilant starts using; tests/test_esi_scope_guard.py
fails if app code calls an ESI path the table does not know.
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

SPEC_URL = "https://esi.evetech.net/meta/openapi.json"
OUT = Path(__file__).resolve().parent.parent / "app" / "esi" / "scope_map.py"
METHODS = ("get", "post", "put", "delete")


def load(src: str | None) -> dict:
    if src:
        return json.loads(Path(src).read_text())
    req = urllib.request.Request(SPEC_URL, headers={"User-Agent": "vigilant-scope-map-generator"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def main() -> int:
    spec = load(sys.argv[1] if len(sys.argv) > 1 else None)
    auth, public = [], []
    for path, ops in sorted(spec["paths"].items()):
        for method in METHODS:
            op = ops.get(method)
            if not isinstance(op, dict):
                continue
            scopes = sorted({s for entry in (op.get("security") or []) for v in entry.values() for s in v})
            if len(scopes) > 1:
                raise SystemExit(f"{method.upper()} {path} needs {scopes}; the guard assumes one scope per operation")
            if scopes:
                auth.append((method.upper(), path, scopes[0], tuple(op.get("x-required-roles") or ())))
            else:
                public.append((method.upper(), path))

    lines = [
        '"""GENERATED by scripts/gen_esi_scope_map.py from the ESI OpenAPI spec — do not edit by hand.',
        "",
        f"Spec: {SPEC_URL} (info.version {spec.get('info', {}).get('version', '?')}).",
        "AUTH_OPS: (method, path template, required scope, in-game roles — any one suffices).",
        "PUBLIC_OPS: (method, path template) for operations that need no token.",
        '"""',
        "",
        "AUTH_OPS: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (",
    ]
    lines += [f"    ({m!r}, {p!r}, {s!r}, {r!r})," for m, p, s, r in auth]
    lines += [")", "", "PUBLIC_OPS: tuple[tuple[str, str], ...] = ("]
    lines += [f"    ({m!r}, {p!r})," for m, p in public]
    lines += [")", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} — {len(auth)} authenticated, {len(public)} public operations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
