"""Dogma attribute ID constants used by the fitting engine."""

# Ship base stats
ATTR_HP = 9
ATTR_SHIELD_HP = 263
ATTR_ARMOR_HP = 265
ATTR_POWER_OUTPUT = 11
ATTR_CPU_OUTPUT = 48
ATTR_CAPACITOR = 482
ATTR_CAP_RECHARGE = 55
ATTR_MAX_VELOCITY = 37
ATTR_MASS = 4
ATTR_INERTIA = 70
ATTR_SIG_RADIUS = 552
ATTR_CARGO_CAPACITY = 38
ATTR_DRONE_CAPACITY = 283
ATTR_DRONE_BANDWIDTH = 1271
ATTR_MAX_TARGET_RANGE = 76
ATTR_MAX_LOCKED_TARGETS = 192
ATTR_SCAN_RESOLUTION = 564
ATTR_CALIBRATION_OUTPUT = 1132
ATTR_RIG_SIZE = 1547

# Ship slot counts (NOTE: 12=low, 14=high — counterintuitive SDE naming)
ATTR_LOW_SLOTS = 12
ATTR_MED_SLOTS = 13
ATTR_HI_SLOTS = 14
ATTR_RIG_SLOTS = 1137
ATTR_TURRET_SLOTS = 102
ATTR_LAUNCHER_SLOTS = 101

# Module fitting requirements
ATTR_POWER = 30
ATTR_CPU = 50
ATTR_UPGRADE_COST = 1153

# Module activation
ATTR_CAPACITOR_NEED = 6    # cap per activation (GJ)
ATTR_DURATION = 73         # cycle time (ms)

# Drone attributes
ATTR_DRONE_BW_USED = 1272
ATTR_VOLUME = 161

# Shield recharge
ATTR_SHIELD_RECHARGE_RATE = 479  # shield recharge time (ms)

# Weapon / damage attributes
ATTR_DAMAGE_MULTIPLIER = 64    # turret/drone damage multiplier
ATTR_RATE_OF_FIRE = 51         # turret/launcher ROF (ms) — "speed" attribute
ATTR_OPTIMAL_RANGE = 54        # maxRange
ATTR_FALLOFF = 158
ATTR_TRACKING_SPEED = 160
ATTR_EM_DAMAGE = 114
ATTR_EXPLOSIVE_DAMAGE = 116
ATTR_KINETIC_DAMAGE = 117
ATTR_THERMAL_DAMAGE = 118

# Charge compatibility
ATTR_CHARGE_SIZE = 128
ATTR_CHARGE_GROUP_1 = 604
ATTR_CHARGE_GROUP_2 = 605
ATTR_CHARGE_GROUP_3 = 606
ATTR_CHARGE_GROUP_4 = 607
ATTR_CHARGE_GROUP_5 = 610
CHARGE_GROUP_ATTRS = [604, 605, 606, 607, 610]

# Sensor strength
ATTR_SCAN_GRAVIMETRIC = 211
ATTR_SCAN_LADAR = 209
ATTR_SCAN_MAGNETOMETRIC = 210
ATTR_SCAN_RADAR = 208

# Shield resists (damage resonance: 1 - resist)
ATTR_SHIELD_EM_RESONANCE = 271
ATTR_SHIELD_THERM_RESONANCE = 274
ATTR_SHIELD_KIN_RESONANCE = 273
ATTR_SHIELD_EXPL_RESONANCE = 272

# Armor resists
ATTR_ARMOR_EM_RESONANCE = 267
ATTR_ARMOR_THERM_RESONANCE = 270
ATTR_ARMOR_KIN_RESONANCE = 269
ATTR_ARMOR_EXPL_RESONANCE = 268

# Hull resists
ATTR_HULL_EM_RESONANCE = 974
ATTR_HULL_THERM_RESONANCE = 977
ATTR_HULL_KIN_RESONANCE = 976
ATTR_HULL_EXPL_RESONANCE = 975

SHIP_STAT_ATTRS = {
    "hull_hp": ATTR_HP,
    "armor_hp": ATTR_ARMOR_HP,
    "shield_hp": ATTR_SHIELD_HP,
    "pg_output": ATTR_POWER_OUTPUT,
    "cpu_output": ATTR_CPU_OUTPUT,
    "capacitor": ATTR_CAPACITOR,
    "cap_recharge": ATTR_CAP_RECHARGE,
    "max_velocity": ATTR_MAX_VELOCITY,
    "mass": ATTR_MASS,
    "inertia": ATTR_INERTIA,
    "sig_radius": ATTR_SIG_RADIUS,
    "cargo_capacity": ATTR_CARGO_CAPACITY,
    "drone_capacity": ATTR_DRONE_CAPACITY,
    "drone_bandwidth": ATTR_DRONE_BANDWIDTH,
    "max_target_range": ATTR_MAX_TARGET_RANGE,
    "max_locked_targets": ATTR_MAX_LOCKED_TARGETS,
    "scan_resolution": ATTR_SCAN_RESOLUTION,
    "calibration_output": ATTR_CALIBRATION_OUTPUT,
    "hi_slots": ATTR_HI_SLOTS,
    "med_slots": ATTR_MED_SLOTS,
    "low_slots": ATTR_LOW_SLOTS,
    "rig_slots": ATTR_RIG_SLOTS,
    "turret_slots": ATTR_TURRET_SLOTS,
    "launcher_slots": ATTR_LAUNCHER_SLOTS,
}
